[2024-11-05T15:48:52.602+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-05T15:48:52.633+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_To_Data_Warehouse.load_data_to_Stg_DimNCC manual__2024-11-05T15:48:48.080577+00:00 [queued]>
[2024-11-05T15:48:52.645+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_To_Data_Warehouse.load_data_to_Stg_DimNCC manual__2024-11-05T15:48:48.080577+00:00 [queued]>
[2024-11-05T15:48:52.646+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-05T15:48:52.659+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): load_data_to_Stg_DimNCC> on 2024-11-05 15:48:48.080577+00:00
[2024-11-05T15:48:52.664+0000] {standard_task_runner.py:63} INFO - Started process 11550 to run task
[2024-11-05T15:48:52.667+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_To_Data_Warehouse', 'load_data_to_Stg_DimNCC', 'manual__2024-11-05T15:48:48.080577+00:00', '--job-id', '274', '--raw', '--subdir', 'DAGS_FOLDER/ETL_LDTBXH.dag.py', '--cfg-path', '/tmp/tmp2r3e_qgp']
[2024-11-05T15:48:52.668+0000] {standard_task_runner.py:91} INFO - Job 274: Subtask load_data_to_Stg_DimNCC
[2024-11-05T15:48:52.730+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_To_Data_Warehouse.load_data_to_Stg_DimNCC manual__2024-11-05T15:48:48.080577+00:00 [running]> on host 3d0ab7361361
[2024-11-05T15:48:53.194+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_To_Data_Warehouse' AIRFLOW_CTX_TASK_ID='load_data_to_Stg_DimNCC' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T15:48:48.080577+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-05T15:48:48.080577+00:00'
[2024-11-05T15:48:53.196+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-05T15:48:53.198+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-05T15:48:53.201+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python otp/***/plugins/NCC/load_api_to_stgNCC.py']
[2024-11-05T15:48:53.236+0000] {subprocess.py:86} INFO - Output:
[2024-11-05T15:48:53.371+0000] {subprocess.py:93} INFO - python: can't open file '/tmp/***tmpw_1sc7e8/otp/***/plugins/NCC/load_api_to_stgNCC.py': [Errno 2] No such file or directory
[2024-11-05T15:48:53.377+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-11-05T15:48:53.379+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-05T15:48:53.395+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-11-05T15:48:53.403+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ETL_To_Data_Warehouse, task_id=load_data_to_Stg_DimNCC, run_id=manual__2024-11-05T15:48:48.080577+00:00, execution_date=20241105T154848, start_date=20241105T154852, end_date=20241105T154853
[2024-11-05T15:48:53.429+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 274 for task load_data_to_Stg_DimNCC (Bash command failed. The command returned a non-zero exit code 2.; 11550)
[2024-11-05T15:48:53.487+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-05T15:48:53.532+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-05T15:48:53.541+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
