[2024-11-12T01:25:45.079+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-12T01:25:45.114+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_To_Data_Warehouse.load_data_to_stgBenef manual__2024-11-12T01:24:54.300922+00:00 [queued]>
[2024-11-12T01:25:45.128+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_To_Data_Warehouse.load_data_to_stgBenef manual__2024-11-12T01:24:54.300922+00:00 [queued]>
[2024-11-12T01:25:45.129+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-12T01:25:45.150+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data_to_stgBenef> on 2024-11-12 01:24:54.300922+00:00
[2024-11-12T01:25:45.160+0000] {standard_task_runner.py:63} INFO - Started process 1268 to run task
[2024-11-12T01:25:45.164+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_To_Data_Warehouse', 'load_data_to_stgBenef', 'manual__2024-11-12T01:24:54.300922+00:00', '--job-id', '615', '--raw', '--subdir', 'DAGS_FOLDER/ETL_LDTBXH.dag.py', '--cfg-path', '/tmp/tmp1kkc8w58']
[2024-11-12T01:25:45.166+0000] {standard_task_runner.py:91} INFO - Job 615: Subtask load_data_to_stgBenef
[2024-11-12T01:25:45.245+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_To_Data_Warehouse.load_data_to_stgBenef manual__2024-11-12T01:24:54.300922+00:00 [running]> on host 3d0ab7361361
[2024-11-12T01:25:45.394+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_To_Data_Warehouse' AIRFLOW_CTX_TASK_ID='load_data_to_stgBenef' AIRFLOW_CTX_EXECUTION_DATE='2024-11-12T01:24:54.300922+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-12T01:24:54.300922+00:00'
[2024-11-12T01:25:45.397+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-12T01:25:45.443+0000] {logging_mixin.py:188} INFO - Kết nối đến MySQL thành công
[2024-11-12T01:25:45.453+0000] {logging_mixin.py:188} INFO - Error fetching data from API: HTTPConnectionPool(host='host.docker.internal', port=8000): Max retries exceeded with url: /benef (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5de4fca10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-12T01:25:45.453+0000] {logging_mixin.py:188} INFO - Không có dữ liệu để chèn.
[2024-11-12T01:25:45.454+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-12T01:25:45.454+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-12T01:25:45.464+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ETL_To_Data_Warehouse, task_id=load_data_to_stgBenef, run_id=manual__2024-11-12T01:24:54.300922+00:00, execution_date=20241112T012454, start_date=20241112T012545, end_date=20241112T012545
[2024-11-12T01:25:45.498+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-12T01:25:45.527+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-12T01:25:45.532+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
