[2024-11-13T01:32:05.831+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-13T01:32:05.865+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_To_Data_Warehouse.load_data_to_stgNCC manual__2024-11-13T01:32:00.391380+00:00 [queued]>
[2024-11-13T01:32:05.874+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_To_Data_Warehouse.load_data_to_stgNCC manual__2024-11-13T01:32:00.391380+00:00 [queued]>
[2024-11-13T01:32:05.874+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-13T01:32:05.891+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data_to_stgNCC> on 2024-11-13 01:32:00.391380+00:00
[2024-11-13T01:32:05.898+0000] {standard_task_runner.py:63} INFO - Started process 1252 to run task
[2024-11-13T01:32:05.904+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_To_Data_Warehouse', 'load_data_to_stgNCC', 'manual__2024-11-13T01:32:00.391380+00:00', '--job-id', '755', '--raw', '--subdir', 'DAGS_FOLDER/ETL_LDTBXH.dag.py', '--cfg-path', '/tmp/tmpr12oxjik']
[2024-11-13T01:32:05.905+0000] {standard_task_runner.py:91} INFO - Job 755: Subtask load_data_to_stgNCC
[2024-11-13T01:32:05.975+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_To_Data_Warehouse.load_data_to_stgNCC manual__2024-11-13T01:32:00.391380+00:00 [running]> on host 3d0ab7361361
[2024-11-13T01:32:06.392+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_To_Data_Warehouse' AIRFLOW_CTX_TASK_ID='load_data_to_stgNCC' AIRFLOW_CTX_EXECUTION_DATE='2024-11-13T01:32:00.391380+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-13T01:32:00.391380+00:00'
[2024-11-13T01:32:06.394+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-13T01:32:06.448+0000] {logging_mixin.py:188} INFO - Kết nối đến MySQL thành công
[2024-11-13T01:33:36.920+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-11-13T01:33:36.920+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-11-13T01:33:36.922+0000] {process_utils.py:132} INFO - Sending 15 to group 1252. PIDs of all processes in the group: [1252]
[2024-11-13T01:33:36.922+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 1252
[2024-11-13T01:33:36.923+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-11-13T01:33:36.924+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-13T01:33:36.975+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1252, status='terminated', exitcode=0, started='01:32:05') (1252) terminated with exit code 0
