[2024-11-12T06:05:10.364+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-12T06:05:10.390+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_To_Data_Warehouse.clear_data_to_stgFact manual__2024-11-12T06:04:35.257517+00:00 [queued]>
[2024-11-12T06:05:10.399+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_To_Data_Warehouse.clear_data_to_stgFact manual__2024-11-12T06:04:35.257517+00:00 [queued]>
[2024-11-12T06:05:10.400+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-12T06:05:10.411+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): clear_data_to_stgFact> on 2024-11-12 06:04:35.257517+00:00
[2024-11-12T06:05:10.417+0000] {standard_task_runner.py:63} INFO - Started process 91526 to run task
[2024-11-12T06:05:10.420+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_To_Data_Warehouse', 'clear_data_to_stgFact', 'manual__2024-11-12T06:04:35.257517+00:00', '--job-id', '744', '--raw', '--subdir', 'DAGS_FOLDER/ETL_LDTBXH.dag.py', '--cfg-path', '/tmp/tmp9_tiamyu']
[2024-11-12T06:05:10.421+0000] {standard_task_runner.py:91} INFO - Job 744: Subtask clear_data_to_stgFact
[2024-11-12T06:05:10.473+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_To_Data_Warehouse.clear_data_to_stgFact manual__2024-11-12T06:04:35.257517+00:00 [running]> on host 3d0ab7361361
[2024-11-12T06:05:10.733+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_To_Data_Warehouse' AIRFLOW_CTX_TASK_ID='clear_data_to_stgFact' AIRFLOW_CTX_EXECUTION_DATE='2024-11-12T06:04:35.257517+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-12T06:04:35.257517+00:00'
[2024-11-12T06:05:10.734+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-12T06:05:10.776+0000] {logging_mixin.py:188} WARNING - /opt/***/plugins/NCC/clear_data_stgFact.py:16 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-11-12T06:05:17.376+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-12T06:05:17.377+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-12T06:05:17.387+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ETL_To_Data_Warehouse, task_id=clear_data_to_stgFact, run_id=manual__2024-11-12T06:04:35.257517+00:00, execution_date=20241112T060435, start_date=20241112T060510, end_date=20241112T060517
[2024-11-12T06:05:17.425+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-12T06:05:17.675+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-12T06:05:17.677+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
