[2024-11-12T04:31:58.244+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-12T04:31:58.289+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_To_Data_Warehouse.load_data_to_stgFact manual__2024-11-12T04:31:52.608403+00:00 [queued]>
[2024-11-12T04:31:58.303+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_To_Data_Warehouse.load_data_to_stgFact manual__2024-11-12T04:31:52.608403+00:00 [queued]>
[2024-11-12T04:31:58.304+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-12T04:31:58.322+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data_to_stgFact> on 2024-11-12 04:31:52.608403+00:00
[2024-11-12T04:31:58.331+0000] {standard_task_runner.py:63} INFO - Started process 42848 to run task
[2024-11-12T04:31:58.335+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_To_Data_Warehouse', 'load_data_to_stgFact', 'manual__2024-11-12T04:31:52.608403+00:00', '--job-id', '692', '--raw', '--subdir', 'DAGS_FOLDER/ETL_LDTBXH.dag.py', '--cfg-path', '/tmp/tmpvtdv9k7g']
[2024-11-12T04:31:58.337+0000] {standard_task_runner.py:91} INFO - Job 692: Subtask load_data_to_stgFact
[2024-11-12T04:31:58.420+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_To_Data_Warehouse.load_data_to_stgFact manual__2024-11-12T04:31:52.608403+00:00 [running]> on host 3d0ab7361361
[2024-11-12T04:31:59.037+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_To_Data_Warehouse' AIRFLOW_CTX_TASK_ID='load_data_to_stgFact' AIRFLOW_CTX_EXECUTION_DATE='2024-11-12T04:31:52.608403+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-12T04:31:52.608403+00:00'
[2024-11-12T04:31:59.039+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-12T04:31:59.115+0000] {logging_mixin.py:188} INFO - Kết nối đến MySQL thành công
[2024-11-12T04:32:03.092+0000] {logging_mixin.py:188} INFO - Error fetching data from API: 500 Server Error: Internal Server Error for url: http://host.docker.internal:8000/BaoCaoNCC
[2024-11-12T04:32:03.105+0000] {logging_mixin.py:188} INFO - Không có dữ liệu để chèn.
[2024-11-12T04:32:03.110+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-12T04:32:03.111+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-12T04:32:03.156+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ETL_To_Data_Warehouse, task_id=load_data_to_stgFact, run_id=manual__2024-11-12T04:31:52.608403+00:00, execution_date=20241112T043152, start_date=20241112T043158, end_date=20241112T043203
[2024-11-12T04:32:03.283+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-12T04:32:03.305+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
