[2024-10-30T09:20:03.911+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-30T09:20:03.936+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_To_Data_Warehouse.load_date_stage manual__2024-10-30T09:19:59.500487+00:00 [queued]>
[2024-10-30T09:20:03.943+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_To_Data_Warehouse.load_date_stage manual__2024-10-30T09:19:59.500487+00:00 [queued]>
[2024-10-30T09:20:03.944+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-30T09:20:03.959+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_date_stage> on 2024-10-30 09:19:59.500487+00:00
[2024-10-30T09:20:03.966+0000] {standard_task_runner.py:63} INFO - Started process 1813 to run task
[2024-10-30T09:20:03.969+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_To_Data_Warehouse', 'load_date_stage', 'manual__2024-10-30T09:19:59.500487+00:00', '--job-id', '124', '--raw', '--subdir', 'DAGS_FOLDER/ETL_LDTBXH.dag.py', '--cfg-path', '/tmp/tmp0_hk3h21']
[2024-10-30T09:20:03.970+0000] {standard_task_runner.py:91} INFO - Job 124: Subtask load_date_stage
[2024-10-30T09:20:04.013+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_To_Data_Warehouse.load_date_stage manual__2024-10-30T09:19:59.500487+00:00 [running]> on host 3d0ab7361361
[2024-10-30T09:20:04.271+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_To_Data_Warehouse' AIRFLOW_CTX_TASK_ID='load_date_stage' AIRFLOW_CTX_EXECUTION_DATE='2024-10-30T09:19:59.500487+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-30T09:19:59.500487+00:00'
[2024-10-30T09:20:04.272+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-30T09:20:04.654+0000] {logging_mixin.py:188} INFO - Starting insertion...
[2024-10-30T09:20:04.668+0000] {logging_mixin.py:188} INFO - Error: 1146 (42S02): Table 'ldtbxh_stg.stgdate' doesn't exist
[2024-10-30T09:20:04.671+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-30T09:20:04.671+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-30T09:20:04.680+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ETL_To_Data_Warehouse, task_id=load_date_stage, run_id=manual__2024-10-30T09:19:59.500487+00:00, execution_date=20241030T091959, start_date=20241030T092003, end_date=20241030T092004
[2024-10-30T09:20:04.704+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-30T09:20:04.875+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-30T09:20:04.878+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
