[2024-11-06T07:43:47.528+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-06T07:43:47.556+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_To_Data_Warehouse.load_data_to_stgNCC manual__2024-11-06T07:43:42.737421+00:00 [queued]>
[2024-11-06T07:43:47.568+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_To_Data_Warehouse.load_data_to_stgNCC manual__2024-11-06T07:43:42.737421+00:00 [queued]>
[2024-11-06T07:43:47.569+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-06T07:43:47.581+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data_to_stgNCC> on 2024-11-06 07:43:42.737421+00:00
[2024-11-06T07:43:47.587+0000] {standard_task_runner.py:63} INFO - Started process 48478 to run task
[2024-11-06T07:43:47.597+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_To_Data_Warehouse', 'load_data_to_stgNCC', 'manual__2024-11-06T07:43:42.737421+00:00', '--job-id', '474', '--raw', '--subdir', 'DAGS_FOLDER/ETL_LDTBXH.dag.py', '--cfg-path', '/tmp/tmpq2jg5oz4']
[2024-11-06T07:43:47.599+0000] {standard_task_runner.py:91} INFO - Job 474: Subtask load_data_to_stgNCC
[2024-11-06T07:43:47.685+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_To_Data_Warehouse.load_data_to_stgNCC manual__2024-11-06T07:43:42.737421+00:00 [running]> on host 3d0ab7361361
[2024-11-06T07:43:47.984+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_To_Data_Warehouse' AIRFLOW_CTX_TASK_ID='load_data_to_stgNCC' AIRFLOW_CTX_EXECUTION_DATE='2024-11-06T07:43:42.737421+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-06T07:43:42.737421+00:00'
[2024-11-06T07:43:47.985+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-06T07:43:48.069+0000] {logging_mixin.py:188} INFO - Kết nối đến MySQL thành công
[2024-11-06T07:43:48.075+0000] {logging_mixin.py:188} INFO - Error fetching data from API: HTTPConnectionPool(host='host.docker.internal', port=8000): Max retries exceeded with url: /NCC (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5586554e50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-06T07:43:48.076+0000] {logging_mixin.py:188} INFO - Không có dữ liệu để chèn.
[2024-11-06T07:43:48.076+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-06T07:43:48.077+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-06T07:43:48.086+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ETL_To_Data_Warehouse, task_id=load_data_to_stgNCC, run_id=manual__2024-11-06T07:43:42.737421+00:00, execution_date=20241106T074342, start_date=20241106T074347, end_date=20241106T074348
[2024-11-06T07:43:48.130+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-06T07:43:48.155+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-06T07:43:48.157+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
