[2024-11-13T01:32:05.857+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-13T01:32:05.890+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_To_Data_Warehouse.load_data_to_stgFact manual__2024-11-13T01:32:00.391380+00:00 [queued]>
[2024-11-13T01:32:05.904+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_To_Data_Warehouse.load_data_to_stgFact manual__2024-11-13T01:32:00.391380+00:00 [queued]>
[2024-11-13T01:32:05.905+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-13T01:32:05.922+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data_to_stgFact> on 2024-11-13 01:32:00.391380+00:00
[2024-11-13T01:32:05.932+0000] {standard_task_runner.py:63} INFO - Started process 1254 to run task
[2024-11-13T01:32:05.938+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_To_Data_Warehouse', 'load_data_to_stgFact', 'manual__2024-11-13T01:32:00.391380+00:00', '--job-id', '757', '--raw', '--subdir', 'DAGS_FOLDER/ETL_LDTBXH.dag.py', '--cfg-path', '/tmp/tmpaiadkrxi']
[2024-11-13T01:32:05.940+0000] {standard_task_runner.py:91} INFO - Job 757: Subtask load_data_to_stgFact
[2024-11-13T01:32:06.005+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_To_Data_Warehouse.load_data_to_stgFact manual__2024-11-13T01:32:00.391380+00:00 [running]> on host 3d0ab7361361
[2024-11-13T01:32:06.438+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_To_Data_Warehouse' AIRFLOW_CTX_TASK_ID='load_data_to_stgFact' AIRFLOW_CTX_EXECUTION_DATE='2024-11-13T01:32:00.391380+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-13T01:32:00.391380+00:00'
[2024-11-13T01:32:06.440+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-13T01:32:06.498+0000] {logging_mixin.py:188} INFO - Kết nối đến MySQL thành công
[2024-11-13T01:33:36.960+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-11-13T01:33:36.961+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-11-13T01:33:36.962+0000] {process_utils.py:132} INFO - Sending 15 to group 1254. PIDs of all processes in the group: [1254]
[2024-11-13T01:33:36.962+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 1254
[2024-11-13T01:33:36.963+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-11-13T01:33:36.964+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-13T01:33:37.015+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1254, status='terminated', exitcode=0, started='01:32:05') (1254) terminated with exit code 0
