[2024-10-30T09:21:16.469+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-30T09:21:16.498+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_To_Data_Warehouse.load_date_stage manual__2024-10-30T09:21:11.804676+00:00 [queued]>
[2024-10-30T09:21:16.506+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_To_Data_Warehouse.load_date_stage manual__2024-10-30T09:21:11.804676+00:00 [queued]>
[2024-10-30T09:21:16.507+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-30T09:21:16.518+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_date_stage> on 2024-10-30 09:21:11.804676+00:00
[2024-10-30T09:21:16.525+0000] {standard_task_runner.py:63} INFO - Started process 2358 to run task
[2024-10-30T09:21:16.527+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_To_Data_Warehouse', 'load_date_stage', 'manual__2024-10-30T09:21:11.804676+00:00', '--job-id', '130', '--raw', '--subdir', 'DAGS_FOLDER/ETL_LDTBXH.dag.py', '--cfg-path', '/tmp/tmp14ycehoc']
[2024-10-30T09:21:16.528+0000] {standard_task_runner.py:91} INFO - Job 130: Subtask load_date_stage
[2024-10-30T09:21:16.571+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_To_Data_Warehouse.load_date_stage manual__2024-10-30T09:21:11.804676+00:00 [running]> on host 3d0ab7361361
[2024-10-30T09:21:16.839+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_To_Data_Warehouse' AIRFLOW_CTX_TASK_ID='load_date_stage' AIRFLOW_CTX_EXECUTION_DATE='2024-10-30T09:21:11.804676+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-30T09:21:11.804676+00:00'
[2024-10-30T09:21:16.840+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-30T09:21:17.194+0000] {logging_mixin.py:188} INFO - Starting insertion...
[2024-10-30T09:21:17.203+0000] {logging_mixin.py:188} INFO - Error: 1146 (42S02): Table 'ldtbxh_stg.stgdate' doesn't exist
[2024-10-30T09:21:17.207+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-30T09:21:17.208+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-30T09:21:17.215+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ETL_To_Data_Warehouse, task_id=load_date_stage, run_id=manual__2024-10-30T09:21:11.804676+00:00, execution_date=20241030T092111, start_date=20241030T092116, end_date=20241030T092117
[2024-10-30T09:21:17.263+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-30T09:21:17.447+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-30T09:21:17.449+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
