[2024-10-30T07:42:05.385+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-30T07:42:05.408+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_To_Data_Warehouse.update_measure_stage_hongheo manual__2024-10-30T07:42:00.530514+00:00 [queued]>
[2024-10-30T07:42:05.416+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_To_Data_Warehouse.update_measure_stage_hongheo manual__2024-10-30T07:42:00.530514+00:00 [queued]>
[2024-10-30T07:42:05.417+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-30T07:42:05.429+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): update_measure_stage_hongheo> on 2024-10-30 07:42:00.530514+00:00
[2024-10-30T07:42:05.436+0000] {standard_task_runner.py:63} INFO - Started process 4019 to run task
[2024-10-30T07:42:05.438+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_To_Data_Warehouse', 'update_measure_stage_hongheo', 'manual__2024-10-30T07:42:00.530514+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/ETL_LDTBXH.dag.py', '--cfg-path', '/tmp/tmpasr30afp']
[2024-10-30T07:42:05.439+0000] {standard_task_runner.py:91} INFO - Job 42: Subtask update_measure_stage_hongheo
[2024-10-30T07:42:05.490+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_To_Data_Warehouse.update_measure_stage_hongheo manual__2024-10-30T07:42:00.530514+00:00 [running]> on host 3d0ab7361361
[2024-10-30T07:42:05.558+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_To_Data_Warehouse' AIRFLOW_CTX_TASK_ID='update_measure_stage_hongheo' AIRFLOW_CTX_EXECUTION_DATE='2024-10-30T07:42:00.530514+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-30T07:42:00.530514+00:00'
[2024-10-30T07:42:05.560+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-30T07:42:05.561+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-30T07:42:05.562+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python ./plugins/HoNgheo/Transform.py']
[2024-10-30T07:42:05.574+0000] {subprocess.py:86} INFO - Output:
[2024-10-30T07:42:05.621+0000] {subprocess.py:93} INFO - python: can't open file '/tmp/***tmp8zxlg6i3/./plugins/HoNgheo/Transform.py': [Errno 2] No such file or directory
[2024-10-30T07:42:05.624+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-10-30T07:42:05.625+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-30T07:42:05.634+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-10-30T07:42:05.639+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ETL_To_Data_Warehouse, task_id=update_measure_stage_hongheo, run_id=manual__2024-10-30T07:42:00.530514+00:00, execution_date=20241030T074200, start_date=20241030T074205, end_date=20241030T074205
[2024-10-30T07:42:05.649+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 42 for task update_measure_stage_hongheo (Bash command failed. The command returned a non-zero exit code 2.; 4019)
[2024-10-30T07:42:05.692+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-30T07:42:05.711+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-30T07:42:05.716+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
