[2024-10-30T08:03:43.381+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-30T08:03:43.411+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_To_Data_Warehouse.update_measure_stage_hongheo manual__2024-10-30T08:03:38.574635+00:00 [queued]>
[2024-10-30T08:03:43.419+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_To_Data_Warehouse.update_measure_stage_hongheo manual__2024-10-30T08:03:38.574635+00:00 [queued]>
[2024-10-30T08:03:43.420+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-30T08:03:43.434+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): update_measure_stage_hongheo> on 2024-10-30 08:03:38.574635+00:00
[2024-10-30T08:03:43.441+0000] {standard_task_runner.py:63} INFO - Started process 15585 to run task
[2024-10-30T08:03:43.447+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_To_Data_Warehouse', 'update_measure_stage_hongheo', 'manual__2024-10-30T08:03:38.574635+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/ETL_LDTBXH.dag.py', '--cfg-path', '/tmp/tmpnaoyyj19']
[2024-10-30T08:03:43.448+0000] {standard_task_runner.py:91} INFO - Job 66: Subtask update_measure_stage_hongheo
[2024-10-30T08:03:43.505+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_To_Data_Warehouse.update_measure_stage_hongheo manual__2024-10-30T08:03:38.574635+00:00 [running]> on host 3d0ab7361361
[2024-10-30T08:03:43.589+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_To_Data_Warehouse' AIRFLOW_CTX_TASK_ID='update_measure_stage_hongheo' AIRFLOW_CTX_EXECUTION_DATE='2024-10-30T08:03:38.574635+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-30T08:03:38.574635+00:00'
[2024-10-30T08:03:43.590+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-30T08:03:43.690+0000] {logging_mixin.py:188} WARNING - /opt/***/plugins/HoNgheo/Transform.py:52 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-10-30T08:03:43.703+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-30T08:03:43.704+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3791, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 152, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 181, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Diem_B1'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/HoNgheo/Transform.py", line 55, in run_transform_fact_hongheo
    result_df = calculate_scores(data_df)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/HoNgheo/Transform.py", line 7, in calculate_scores
    df['TongDiemB1B2'] = df['Diem_B1'] + df['Diem_B2']
                         ~~^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/core/frame.py", line 3893, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3798, in get_loc
    raise KeyError(key) from err
KeyError: 'Diem_B1'
[2024-10-30T08:03:43.720+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ETL_To_Data_Warehouse, task_id=update_measure_stage_hongheo, run_id=manual__2024-10-30T08:03:38.574635+00:00, execution_date=20241030T080338, start_date=20241030T080343, end_date=20241030T080343
[2024-10-30T08:03:43.729+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 66 for task update_measure_stage_hongheo ('Diem_B1'; 15585)
[2024-10-30T08:03:43.740+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-30T08:03:43.763+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-30T08:03:43.768+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
