[2024-11-11T17:46:39.120+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-11T17:46:39.341+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_To_Data_Warehouse.clear_data_to_stgFact manual__2024-11-11T15:59:13.213689+00:00 [queued]>
[2024-11-11T17:46:39.353+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_To_Data_Warehouse.clear_data_to_stgFact manual__2024-11-11T15:59:13.213689+00:00 [queued]>
[2024-11-11T17:46:39.354+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-11T17:46:39.369+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): clear_data_to_stgFact> on 2024-11-11 15:59:13.213689+00:00
[2024-11-11T17:46:39.380+0000] {standard_task_runner.py:63} INFO - Started process 2612 to run task
[2024-11-11T17:46:39.383+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_To_Data_Warehouse', 'clear_data_to_stgFact', 'manual__2024-11-11T15:59:13.213689+00:00', '--job-id', '604', '--raw', '--subdir', 'DAGS_FOLDER/ETL_LDTBXH.dag.py', '--cfg-path', '/tmp/tmp8ho6ntpv']
[2024-11-11T17:46:39.384+0000] {standard_task_runner.py:91} INFO - Job 604: Subtask clear_data_to_stgFact
[2024-11-11T17:46:39.425+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_To_Data_Warehouse.clear_data_to_stgFact manual__2024-11-11T15:59:13.213689+00:00 [running]> on host 3d0ab7361361
[2024-11-11T17:46:39.493+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_To_Data_Warehouse' AIRFLOW_CTX_TASK_ID='clear_data_to_stgFact' AIRFLOW_CTX_EXECUTION_DATE='2024-11-11T15:59:13.213689+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-11T15:59:13.213689+00:00'
[2024-11-11T17:46:39.495+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-11T17:46:39.535+0000] {logging_mixin.py:188} WARNING - /opt/***/plugins/NCC/clear_data_stgFact.py:16 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-11-11T17:46:39.546+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-11T17:46:39.547+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-11T17:46:39.555+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ETL_To_Data_Warehouse, task_id=clear_data_to_stgFact, run_id=manual__2024-11-11T15:59:13.213689+00:00, execution_date=20241111T155913, start_date=20241111T174639, end_date=20241111T174639
[2024-11-11T17:46:39.596+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-11T17:46:39.619+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-11T17:46:39.621+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
